### ISSUE TITLE
Load test solr staging

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pul_solr#174]
We’re using siege https://www.joedog.org/siege-manual/ and a file of randomly-generated search result urls.

Question: If we slam catalog-staging with requests, which crashes first: solr or nginx/passenger?

Follow-up Question: How do we get solr-staging to crash?

Steps:

- [x] Add solr-staging and catalog-staging to datadog. This will give us access to the same logs we have on solr prod.
- [x] Create a datadog dashboard that will show us everything we want to monitor
- [x] Create a datadog notebook to use as a template for each test run
- [ ] Run tests
- [ ] Remove solr-staging and catalog-staging from datadog

Testing:

Hit catalog-staging with randomly-ordered requests in stages, gradually increasing the entries in urls.txt by a factor of 10.

Restart the solr-staging machines between each test run.

Monitor nginx on the catalog-staging boxes, monitor solr-staging cluster via a datadog dashboard designed for this purpose.

**Comment by hackmastera** [comment]
Wrapped this up for now; made #185 for the datadog removal

**Comment by hackartisan** [comment]
The siege command I used for this work was:
`$ siege --concurrent=25 --time=5m --no-parser --file=urls.txt`

Turning off the parser stops it from downloading images and js files and stuff -- in this case I wanted that because I was trying to stress solr and not the webserver. The time switch tells it to just go for that long and then stop.
