### ISSUE TITLE
solr backups not running on solr7 production

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pul_solr#297]
prod backups are happening fine on solr8.

Solr7 backups are broken on lib-solr2/3 because the solr_backup mounts are mounted as the wrong UID -- the uid of the deploy user is not consistent across machines. So solr tries to create the backup, tells the leader to dump to the mount, and the leader fails if it's not solr1.

You can force the leader to solr1 if you need to generate a backup manually by turning off solr on whichever machine is the current leader.

**Comment by acozine** [comment]
Also, we should monitor the backups and alert if they don't happen / are 0 bytes long.

**Comment by acozine** [comment]
@tpendragon investigated, backups are failing on Solr 2/3 because the mounted drive for backups is not owned by the correct user.

All three Solr servers should be capable of running the backups as the leader of the cluster. Fix the current mounting system:
- [ ] mount diglibdata1 only once, as `/mnt/solr_backup`
- [ ] use NFS instead of CIFS
- [ ] ensure the owner of the `/mnt/solr_backup` directory is the local `deploy` user, which may have a different UID on each box
- [ ] update `/etc/fstab` so the new configuration will survive a reboot

**Comment by acozine** [comment]
We discussed this in the weekly Ops meeting today, and decided to leave the drives mounted using CIFS. I'd originally suggested we change the mount type because we thought the mount was unreliable. Since that was not, in fact, the problem, we will continue to use CIFS for now.
